package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// AMOLED black with restrained khaki accents; light mode remains available.
internal object KhakiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFB4BE86),
        onPrimary = Color(0xFF171A10),
        primaryContainer = Color(0xFF313823),
        onPrimaryContainer = Color(0xFFDAE5AF),
        secondary = Color(0xFFB4BE86),
        onSecondary = Color(0xFF171A10),
        secondaryContainer = Color(0xFF282D1E),
        onSecondaryContainer = Color(0xFFDDE5C2),
        tertiary = Color(0xFFAFC9AE),
        onTertiary = Color(0xFF172B19),
        tertiaryContainer = Color(0xFF2E4430),
        onTertiaryContainer = Color(0xFFD3E8CF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF000000),
        onBackground = Color(0xFFF1F1ED),
        surface = Color(0xFF000000),
        onSurface = Color(0xFFF1F1ED),
        surfaceVariant = Color(0xFF191B17),
        onSurfaceVariant = Color(0xFFA3A49D),
        outline = Color(0xFF777B6D),
        outlineVariant = Color(0xFF363930),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF1F1ED),
        inverseOnSurface = Color(0xFF282A24),
        inversePrimary = Color(0xFF556039),
        surfaceDim = Color(0xFF000000),
        surfaceBright = Color(0xFF282A24),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF0C0C0C),
        surfaceContainer = Color(0xFF111111),
        surfaceContainerHigh = Color(0xFF171717),
        surfaceContainerHighest = Color(0xFF202020),
        surfaceTint = Color(0xFFB4BE86),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF556039),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDEE6BD),
        onPrimaryContainer = Color(0xFF1A210F),
        secondary = Color(0xFF556039),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE3E8D2),
        onSecondaryContainer = Color(0xFF2D3322),
        tertiary = Color(0xFF49664A),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCBEAC7),
        onTertiaryContainer = Color(0xFF18361C),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFAFAF6),
        onBackground = Color(0xFF1B1C18),
        surface = Color(0xFFFAFAF6),
        onSurface = Color(0xFF1B1C18),
        surfaceVariant = Color(0xFFE5E7DC),
        onSurfaceVariant = Color(0xFF4C4F44),
        outline = Color(0xFF73776A),
        outlineVariant = Color(0xFFC5C8B9),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF2E3029),
        inverseOnSurface = Color(0xFFF1F1E8),
        inversePrimary = Color(0xFFB4BE86),
        surfaceDim = Color(0xFFD9DCD0),
        surfaceBright = Color(0xFFFAFAF6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3F4EC),
        surfaceContainer = Color(0xFFEDEEE4),
        surfaceContainerHigh = Color(0xFFE7E9DE),
        surfaceContainerHighest = Color(0xFFE1E3D7),
        surfaceTint = Color(0xFF556039),
    )
}
